document.write( '<!-- Top Bar --> \n' );
document.write( '  <div id=\"top-bar\"> \n' );
document.write( '   <h2>Aliwix Team - مجموعة أليويكس</h2> \n' );
document.write( '  </div>\n' );
document.write( '  <!-- The element where the player will be placed --> \n' );
document.write( '  <div id=\"player\"> \n' );
document.write( '   <div id=\"my-video\"></div>\n' );
document.write( '   <script type=\"text/javascript\"> jwplayer(\"my-video\").setup({\n' );
document.write( '   file: \"https://heny007.github.io/hls/duhok.m3u8\",\n' );
document.write( '   image: \"https://scontent.ftun1-2.fna.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/71318015_380217256223031_2019411863581753344_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=85a577&_nc_ohc=fEYS3VxbZ3EAX-wnGVD&_nc_ht=scontent.ftun1-2.fna&oh=1787679960ad14b11c44af14ecf58600&oe=61641E55\",\n' );
document.write( '   sharing: {code: \'<iframe src=\"\'+ window.location.href +\'\" frameborder=\"0\" width=\"800\" height=\"460\"></iframe>\',},\n' );
document.write( '   link : {code: \"\'+ window.location.href +\'\",},   \n' );
document.write( '     title: \'HeNy007\',autostart: \"false\",width: \"97%\",height: \"560\",\n' );
document.write( '     tag:\"HeNy007\",title:\"aliwixplay.netlify.app\",autostart:\"false\",stretching:\"exactfit\",autostretch:\"false\",\n' );
document.write( '     logo:{position:\"bottom-left\",margin:\"25\",file:\"https://github.com/HeNy007/HeNy007.github.io/raw/main/live/20210912_151611.png\",height:\"25\"}, \n' );
document.write( '     flashplayer:\"https://raw.githack.com/HeNy007/HeNy-Ben-Hamed/master/today-matches/jwplayer.flash.swf\",tracks:{file:\"thumbnails.vtt\",kind:\"thumbnails\"} });\n' );
document.write( '      \n' );
document.write( '    </script>\n' );
document.write( '\n' );
document.write( '  <!-- The element where the channel list --> \n' );
document.write( '  \n' );
document.write( '   <ul id=\"container\"></ul> \n' );
document.write( '  </div>\n' );
document.write( '<center>\n' );
document.write( '    <img class=\"animated-gif\" src=\"http://www.enigma2.net/wp-content/uploads/2018/07/iptv-ads.gif\" onclick=\"window.location=\'https://aliwixplay.netlify.app\';\"><br>\n' );
document.write( '<br>\n' );
document.write( '  <div>\n' );
document.write( '  <iframe src=\"https://live.koooragoal.com/\"></iframe>\n' );
document.write( '  </div>\n' );
document.write( '  <script src=\"https://vjs.zencdn.net/7.11.4/video.min.js\"></script> \n' );
document.write( '  <script>\n' );
document.write( '        $.ajax({\n' );
document.write( '                type: \"GET\",\n' );
document.write( '                url: \'.m3u\',\n' );
document.write( '                success: function(message, text, response) {\n' );
document.write( '                    let str = message\n' );
document.write( '                    let array = str.split(\" \")\n' );
document.write( '                    let links = array.filter(x => /[^h]+.m3u8/.test(x)).map(x => x.split(\"n\")).flat().filter(x => /[^h]+.m3u8/.test(x))\n' );
document.write( '                    for (let i of links) {\n' );
document.write( '                        $(\"#container\").append(\"<li>\" + i + \"</li>\")\n' );
document.write( '                    }\n' );
document.write( '                }\n' );
document.write( '            })\n' );
document.write( '            //Click channel to play it\n' );
document.write( '        $(\"#container\").on(\'click\', \'li\', function() {\n' );
document.write( '            var player = videojs(document.querySelector(\'.video-js\'));\n' );
document.write( '            player.src({\n' );
document.write( '                src: $(this).text(),\n' );
document.write( '                type: \'application/x-mpegURL\' /*video type*/\n' );
document.write( '            });\n' );
document.write( '\n' );
document.write( '            player.play();\n' );
document.write( '        });\n' );
document.write( '       \n' );
document.write( '      \n' );
document.write( '     \n' );
document.write( '    \n' );
document.write( '   \n' );
document.write( '  \n' );
document.write( '  \n' );
document.write( '    </script>\n' );
document.write( ' </center>' );
