function writeHTMLasJS(){
	var HeNy007 = "";
	HeNy007 += "<!-- Top Bar --> ";
	HeNy007 += "  <div id=\"top-bar\"> ";
	HeNy007 += "   <h2>Aliwix Team - مجموعة أليويكس</h2> ";
	HeNy007 += "  </div>";
	HeNy007 += "  <!-- The element where the player will be placed --> ";
	HeNy007 += "  <div id=\"player\"> ";
	HeNy007 += "   <div id=\"my-video\"></div>";
	HeNy007 += "   &lt;script type=\"text/javascript\"> jwplayer(\"my-video\").setup({";
	HeNy007 += "   file: \"https://heny007.github.io/hls/duhok.m3u8\",";
	HeNy007 += "   image: \"https://scontent.ftun1-2.fna.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/71318015_380217256223031_2019411863581753344_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=85a577&_nc_ohc=fEYS3VxbZ3EAX-wnGVD&_nc_ht=scontent.ftun1-2.fna&oh=1787679960ad14b11c44af14ecf58600&oe=61641E55\",";
	HeNy007 += "   sharing: {code: '<iframe src=\"'+ window.location.href +'\" frameborder=\"0\" width=\"800\" height=\"460\"></iframe>',},";
	HeNy007 += "   link : {code: \"'+ window.location.href +'\",},   ";
	HeNy007 += "     title: 'HeNy007',autostart: \"false\",width: \"97%\",height: \"560\",";
	HeNy007 += "     tag:\"HeNy007\",title:\"aliwixplay.netlify.app\",autostart:\"false\",stretching:\"exactfit\",autostretch:\"false\",";
	HeNy007 += "     logo:{position:\"bottom-left\",margin:\"25\",file:\"https://github.com/HeNy007/HeNy007.github.io/raw/main/live/20210912_151611.png\",height:\"25\"}, ";
	HeNy007 += "     flashplayer:\"https://raw.githack.com/HeNy007/HeNy-Ben-Hamed/master/today-matches/jwplayer.flash.swf\",tracks:{file:\"thumbnails.vtt\",kind:\"thumbnails\"} });";
	HeNy007 += "      ";
	HeNy007 += "    &lt;/script&gt;";
	HeNy007 += "";
	HeNy007 += "  <!-- The element where the channel list --> ";
	HeNy007 += "  ";
	HeNy007 += "   <ul id=\"container\"></ul> ";
	HeNy007 += "  </div>";
	HeNy007 += "<center>";
	HeNy007 += "    <img class=\"animated-gif\" src=\"http://www.enigma2.net/wp-content/uploads/2018/07/iptv-ads.gif\" onclick=\"window.location='https://aliwixplay.netlify.app';\"><br>";
	HeNy007 += "<br>";
	HeNy007 += "  <div>";
	HeNy007 += "  <iframe src=\"https://live.koooragoal.com/\"></iframe>";
	HeNy007 += "  </div>";
	HeNy007 += "  &lt;script src=\"https://vjs.zencdn.net/7.11.4/video.min.js\">&lt;/script&gt; ";
	HeNy007 += "  &lt;script>";
	HeNy007 += "        $.ajax({";
	HeNy007 += "                type: \"GET\",";
	HeNy007 += "                url: '.m3u',";
	HeNy007 += "                success: function(message, text, response) {";
	HeNy007 += "                    let str = message";
	HeNy007 += "                    let array = str.split(\" \")";
	HeNy007 += "                    let links = array.filter(x => /[^h]+.m3u8/.test(x)).map(x => x.split(\"\\n\")).flat().filter(x => /[^h]+.m3u8/.test(x))";
	HeNy007 += "                    for (let i of links) {";
	HeNy007 += "                        $(\"#container\").append(\"<li>\" + i + \"</li>\")";
	HeNy007 += "                    }";
	HeNy007 += "                }";
	HeNy007 += "            })";
	HeNy007 += "            //Click channel to play it";
	HeNy007 += "        $(\"#container\").on('click', 'li', function() {";
	HeNy007 += "            var player = videojs(document.querySelector('.video-js'));";
	HeNy007 += "            player.src({";
	HeNy007 += "                src: $(this).text(),";
	HeNy007 += "                type: 'application/x-mpegURL' /*video type*/";
	HeNy007 += "            });";
	HeNy007 += "";
	HeNy007 += "            player.play();";
	HeNy007 += "        });";
	HeNy007 += "       ";
	HeNy007 += "      ";
	HeNy007 += "     ";
	HeNy007 += "    ";
	HeNy007 += "   ";
	HeNy007 += "  ";
	HeNy007 += "  ";
	HeNy007 += "    &lt;/script&gt;";
	HeNy007 += " </center>";

	document.getElementById("js_html").innerHTML = HeNy007;
}

writeHTMLasJS();
